//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        public Cours()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string department { get; set; }
        [Required]
        public string section { get; set; }
        [Required]
        public string time { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
